version: "3"

services:
  myapi:
    build: ./api-mock
    command: sh -c "npm install && npm run start"
    ports:
      - 4000:4000
  myui:
    build: ./ui-mock
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    depends_on:
      - myapi
    links:
      - myapi